### ISSUE TITLE
Parameter not field out in steam error

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-api#272]
User gets on the website:
`Error You linked this account already to user with name ''{0}''`
The cause is the following. So Normally the API formats errors like this with arguments before it delivers such as an Exception. The website however simply gets the Error returned as json picks out the details which are not formatted and leaves the args behind. So where is the error website or API.

**Comment by Brutus5000** [comment]
The error is mainly in the API. The formatting is usually done inside the `GlobalControllerExceptionHandler`. I have added a properly formatted message to the Error class in my referenced commit.
If the website would use this one we would be fine.

**Comment by Brutus5000** [comment]
Fixed in the meantime.
