### ISSUE TITLE
Add styling to OAuth login page

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#275]
and make it look more like www.faforever.com

**Comment by SoundharyaKamaraj** [comment]
Can I take it up?

**Comment by Brutus5000** [comment]
Sure, go ahead :)

**Comment by 1-alex98** [comment]
@Brutus5000 see it works

**Comment by Brutus5000** [comment]
Fixed in 0dbbd695f688c1358b7597dd13727cf858fc2594 and 19094d723b1ad9c025ee8f2e0000317e6e171dad
