### ISSUE TITLE
[FEATURE] Send mails to moderators when a new report is submitted via the report form

### ISSUE THREAD

**Issue by Rackover** [micheljung/faf-java-api#288]
Google form sends an email to each moderator mail address when a new report is submitted. This feature is useful and should be done in faf java api aswell.

![image](https://user-images.githubusercontent.com/33836535/48258377-3b970800-e415-11e8-980f-04687644c4cc.png)
![image](https://i.imgur.com/1ULy8pD.png)

The steps would be basically : 
- Whenever a new moderationReport is created via POST
    - For each PLAYER_ID from the table lobby_admin
        - SELECT mail_address FROM `login` WHERE id=PLAYER_ID
        - And then send a mail to each of those address containing : Reporter, Offender, Game ID, Game timecode, Report description.

Don't mind the looks of the email for now, we just need the feature. I'll fancy the email layout later if needed 🙂

**Comment by 1-alex98** [comment]
Sure you want this spam? I would not the way modor will be it will show all unadressed report so I would doubt such a thing is needed.

**Comment by louvenarde** [comment]
Yes it is needed, cause we don't always have mordor opened all the time. If some of us dislike the mails they'll simply put it in the spam mail category (i think some of us have done this now) 
It's preferable we build a system with at least the same features than the google form

**Comment by Brutus5000** [comment]
According to current moderators, this is no longer a requirement.
