### ISSUE TITLE
EventService - Updating events fails

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#291]
When sending a valid request to the `/events/update` route for an existing event uuid an exception is thrown.
**Sample payload:**
```
[{
        'count': 1,
        'playerId': 1,
        'eventId': 'ad193982-e7ca-465c-80b0-5493f9739559'
}]
```

**Exception:** `java.sql.SQLException: Field 'event_id' doesn't have a default value `

**Impact:** Achievements can not be updated from game results.

**First analysis:**
In the EventsService a new `PlayerEvent` is created if not already exists. However the `getEvent` in the `PlayerEvent` is annotated as `insertable = false`. I assume this tells hibernate not to insert it, thus it tries to resolve the default value and fails.
Maybe removing the `insertable = false` already solves the problem

**Acceptance criteria for solution:**
- [ ] Fix the root cause (probably the insertable-flag).
- [ ] Replace `eventRepository.getOne` in the EventsService with `findById` and throw a proper error message if optional is empty
- [ ] Write unit tests for the increment method. Mark the method as `@VisibleForTesting`
- [ ] Write integration tests to actually check MySql behavior (add some achievement test-data into sql fails and preload them - look into other integration tests to find out how to do it)

**Comment by micheljung** [comment]
the labels `beginner` and `good first issue` are semantically the same, can we get rid of one?

**Comment by Brutus5000** [comment]
I don't know which one Github promotes right now, but sure. Go ahead.

**Comment by micheljung** [comment]
As a quick fix, the server could make sure that a failed call to the event service does not prevent the achievement update from being executed.

**Comment by louvenarde** [comment]
> As a quick fix, the server could make sure that a failed call to the event service does not prevent the achievement update from being executed.

it's done already
