### ISSUE TITLE
Map vault: install/play count reset for new versions

### ISSUE THREAD

**Issue by JeroenDeDauw** [micheljung/faf-java-api#297]
When uploading a new version of a map using the versioning system, the play and install counts of the map get reset to 0. This does not appear to be happening for mods.

**Comment by 1-alex98** [comment]
Yeah just look at the code and it is wired and yeah looking at the code it makes sense that this happens

**Comment by 1-alex98** [comment]
I would also expect old versions to get deleted

**Comment by Sheikah45** [comment]
Fixed in #454
