### ISSUE TITLE
HTTP 500 on parameter with wrong type

### ISSUE THREAD

**Issue by Askaholic** [micheljung/faf-java-api#302]
When checking leaderboard with a non-integer player id you get a 500 error. This should rather be a 400 Bad Request with a nice error message, saying to use an integer instead. This could be an issue in other endpoints as well.

```
https://api.faforever.com/leaderboards/global/askaholic

{
  "timestamp": 1546911637788,
  "status": 500,
  "error": "Internal Server Error",
  "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.concurrent.CompletionException: java.lang.NumberFormatException: For input string: \"askaholic\"",
  "path": "/leaderboards/global/askaholic"
}
```

This is caused by calling `Integer.valueOf()` on the input string without handling possible errors. These are the things you have to think about when handling user input...

**Comment by padmano** [comment]
@Brutus5000 I can work on this. What exception to be thrown in case of an invalid data ?

**Comment by Askaholic** [comment]
Look at the `message` field. It contains a stack trace. In this case it was NumberFormatException. In general you’ll want to return appropriate error messages for any parameter of the wrong type

**Comment by Brutus5000** [comment]
@iamTheL The correct response would be HTTP 400 or HTTP 422 (unprocessable entity).

Affected class is LeaderboardController

In this particular case we should however do more than just error catching: It makes sense to take a username as alternative value to a user id, so we would need to make the lookup in the database return and optional and concat the two lookups + orElseThrow exception.

**Comment by padmano** [comment]
@Brutus5000 if the look up has to be done against username and user id I guess it should be go as a feature. Should that be added as under a bug as mentioned above ?

**Comment by Brutus5000** [comment]
However you like, we are kinda flexible here 😁

**Comment by padmano** [comment]
Cool. Then let me fix the issue first. The new feature will check in a new issue.
