### ISSUE TITLE
change steam link error message

### ISSUE THREAD

**Issue by PhilipJFryFAF** [micheljung/faf-java-api#308]
When attempting to link your faf acc to steam while your faf acc already being linked to steam a user gets the following error: `Error: Your account is already bound to another steam ID`

This error message can be somewhat misleading
maybe it would be better to include a line in the message that makes it clear that the acc is linked and the user can log in with the faf client and play

**Comment by Brutus5000** [comment]
duplicate of https://github.com/FAForever/faf-java-api/issues/339
