### ISSUE TITLE
Make api return utf-8 instead of some strange encoding

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-api#310]
![image](https://user-images.githubusercontent.com/19996713/56830998-411fc780-6868-11e9-8b90-96133f71a28e.png)

**Comment by 1-alex98** [comment]
The client throws error when querrying from api because faulty utf-8 byte. This probably would not happen if we actually handed out UTF-8

**Comment by 1-alex98** [comment]
Not sure if adding ;charset=UTF-8 would do

**Comment by Brutus5000** [comment]
I would expect the error to be in the db (most of the columns are non-Unicode)

**Comment by 1-alex98** [comment]
Hmm oh ok

**Comment by 1-alex98** [comment]
It would be pretty cool if we could switch to unicode or better utf-8 in general. I mean we could also make the client look at the charset and then decide how to parse it. But i imagine it to be a pain in the ass. Because it is done by libraries which we might not have full control over
