### ISSUE TITLE
Use email templates from mautic instead of direct html

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#322]
Mautic offers us to send emails via templates. We only need to hand in the variables to be replaced in the templates. Keeps the styling out of the API.

**Comment by axel1200** [comment]
Also if somebody makes the change please make a button for the "change password" URL etc. instead of just a URL

**Comment by DDmit04** [comment]
@Brutus5000 Do you mean using a templating engine (thymeleaf for example)? in this case, can i work on it? I am not very good at HTML/CSS, but I can setup template engine in spring

**Comment by Brutus5000** [comment]
No, the template engine is already in the email service called "Mautic". Right now we just use it like a smtp server, but it offers sending-prestyled html/css emails via http calls. You pass along variables with values which are then used in the template.

This is for registration and password reset emails.

**Comment by Brutus5000** [comment]
Closed due to [faf-stack#199](https://github.com/FAForever/faf-stack/issues/199) and #560
