### ISSUE TITLE
pls fix map upload

### ISSUE THREAD

**Issue by badbwoi** [micheljung/faf-java-api#325]
as far as I know upload via dlc workes like this

![image](https://user-images.githubusercontent.com/28671151/61981954-81274f80-affb-11e9-9ebd-0f298f55d209.png)

But unfortunaltely it interpreted the `-` in the name = `Haven Reef - FAF version` as `_`.  This fucks up the pathing and you end up with a broken map, that leads to four-corners bug (map can not be loaded). the path should be `haven_reef_-_faf_version.v0001` in files and folder , but it is `haven_reef___faf_version.v0001`.
![unknown](https://user-images.githubusercontent.com/28671151/61982477-1e36b800-affd-11e9-969b-5929ce9d7ae8.png)
^^left: map prepared for dlc upload; right: uploaded map with pathing error

pls fix this, so ppl can upload there maps again <3

while I'm at it, I don't get why we have an upload system that requires ppl to "break" there maps so they can be uploaded (e.g. remove important parts like .v000x to upload map correctly) . this part should really be improved. here are some ideas:
-the upload should not work if the given path is not correct
-or you can input whatever you want and it will create all the right paths and file names from `name = x` and `map_version = x` (even in scmap if required)
-add an info how files and pathing should look like, to avoid breaking maps like this while upload..
![scenario_error](https://user-images.githubusercontent.com/28671151/61982321-ae283200-affc-11e9-88b6-25ac3c3b630c.PNG)
![script_error](https://user-images.githubusercontent.com/28671151/61982322-af595f00-affc-11e9-97b1-3d5c55b91671.PNG)

**Comment by 1-alex98** [comment]
FAF is slow if i were u I would Upload it again with a name that only contains letters and numbers

**Comment by 1-alex98** [comment]
https://www.bountysource.com/teams/faforever might help otherwise

**Comment by 1-alex98** [comment]
What we could do would a database migration that replaces | with _. but that would result in a mess

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/61995752-e8411480-b08c-11e9-9d11-3d88858acff8.png)
Forbidden on windows

**Comment by 1-alex98** [comment]
This thing is really fucked up. We can only allow file names valid on linux and windows

**Comment by 1-alex98** [comment]
Also the client crashes if ppl upload faulty characters... Which is still possible i think

**Comment by 1-alex98** [comment]
Well the easiest would probably be to : 
- [ ]  check with both the escaped name and the original if it is an update of an old map
- [ ]  fix the client crashing on invalid file names
- [ ]  replace even stricter including lower casing for Linux if point one is done

**Comment by badbwoi** [comment]
Thx for the info.
I'm aware that only characters can be used, that are valid in windows and linux pathing. But it would also be nice to tackle `|` like errors (maybe with a warning while upload).

I don't get, why the possibility to use standard characters was removed, see first post. These are standard in my eyes  `-`, `+`, `&`, `(`, `)`, `.`, `,`
This removes the ability to give meaningful & structured map names. Because of this  I'm unable to support an upload with a different map name :)

If the map upload works like intended/is fixed, there is no need to update old maps / fix client in my eyes

**Comment by 1-alex98** [comment]
Well imagine we use some new server one day with some fucked up linux version that does not allow + in file name. Idk it is just we would rather be on the save side and only allow working map name that are able to work everywhere. Also I have no idea what map names are allowed on mac. FAF does not work on Mac yet but it could some day

**Comment by Brutus5000** [comment]
I have the following proposal:
Instead of "guessing" the right folder name you just use `{MAP_FOLDER}` and we will replace it with `/maps/haven_reef_-_faf_version.v0001` (or whatever the current foldername is) in the API.

**Comment by badbwoi** [comment]
hello again, I made a pretty picture explaining the irregularities while uploading a map.
If it is possible to use `-` in map name, folder, file and path I would be happy.
I also have "Eye of the Storm - FAF version" ready for upload :)
Why was the minus replaced in the folder name, but not in the filenames?

![map_upload_irregularities](https://user-images.githubusercontent.com/28671151/62293442-ec907780-b468-11e9-9ab0-d267838c3038.png)

@Brutus5000  `haven_reef___faf_version` needs to be replaced with `haven_reef_-_faf_version` in folder and scenario file.

**Comment by Brutus5000** [comment]
I wasn't aware, but there already happens a renaming in the lua files, but we did not apply the special character replacement there. I will have a look at it and fix it somehow.

**Comment by Brutus5000** [comment]
To answer one question first: Why is the minus allowed inside the file names? Because we never touched these files and there were no reported issues so far (mostly because people make the maps on windows and are already bound to the windows restrictions). In theory, we'd need to normalize these filenames as well, but that would just break the map and not the whole vault, so this is out of scope.

---

So I'm still looking into this issue and made some progress understanding how everything works, but I am not sure what the problem can be solved in the API alone...

The map upload works like this:

- You send a map in zip file containing one folder with the lua files
- API extracts the zip file
- API generates a new name for the map derived from the map display name (with all non-alphanumerical characters replaced by `_`) + version
- API renames the folder
- API renames the folder inside all lua files
- API zips the renamed folder (result file name is foldername + zip)

Why did we start the renaming? We had surprisingly many cases where we had broken file names on the server due to people putting special characters into the map name. This directly breaks map vault functionality in the client, because the final zip name is derived from the map display name. This is the reason why I am taking a lot of time to resolve this issue properly because I want to prevent this from happening again.


I tested it with the given map version of yours after renaming the foldername + the folder substring in the lua files and it works as designed on my local machine. The foldername is also replaced in the lua files as expected.


The problem I see here is the Ozonex Editor (or any person) needing/trying to guess the final zip name. As soon as that does not match, the lua files will contain wrong folder paths. However, the final decision on the map name must stay serverside.

---
I can offer 3 solutions:

**Solution 1**
We allow some more special characters and refuse maps with scenario lua map name containing "illegal" characters rather than renaming the map.
___Advantage:___ None compared to the others (just works)
___Disadvantage:___ You still need to match the same zip name the API would generate according to the name in scenario.lua folder name (also must not contain any version suffix)

**Solution 2**
The easiest solution to properly unburden everyone from guessing the right zip file name is to use a placeholder `{MAP_FOLDER}` in the lua files that will be replaced by the API with the correct value. Then you and/or the Ozonex Editor doesn't need to know the rules of character escaping etc.
___Advantage:___ Easy to implement in API and Ozonex Editor also easily applied manually
___Disadvantage:___ You can't test this map before uploading on FAF with the placeholder

**Solution 3**
a) We provide an endpoint and/or a webform where you can upload the scenario lua. It will parse the name and return you the final zip name to put into the lua files.
b) We provide and endpoint and/or a webform where you can give the exact name of the map (same as in scenario.lua). It will parse the name and return you the final zip name to put into the lua files.
___Advantage:___ Works for local test before upload
___Disadvantage:___ More work for Ozonex Editor / manual editors



I personally would go for solution 2, but since I'm not a map maker I can't estimate the impact of the disadvantages.

**Comment by CouncillorMorax** [comment]
@badbwoi  could you explain why "Haven Reef FaF Version" is not sufficient enough? This seems like a heck of a lot of dev time devoted to making a "nicety" while they could be focusing on other matters.

Is the vault upload actually broken or is just these characters?

My opinion is this: alpha-numeric only so nothing has to be done. If there is a very strong reason we need other types please state so.

**Comment by speed2CZ** [comment]
Changing paths inside lua files is one thing, but can it change paths inside scmap as well?

**Comment by badbwoi** [comment]
@Brutus5000 thx for taking the time and giving detailed information and solutions. I don't quiet get Solution 2. You are saying, that we have something like `map_folder = "haven_reef_faf_version";` in the scenario.lua that will be used by the API? If so, sounds like an easy solution. And special characters are still allowed in scenario `name = "Haven Reef - FAF version";` right? 

@CouncillorMorax The vault works if you have only letters and numbers in scenario map name. But  in my eyes its definitely broken. I don't see why the map upload should not be well thought out. We having problems with it, since I can remember.
Here are my reasons: 
1)Upload works all the time, but allows upload of broken content and even breaks map in some cases. I broke 75% of my .v0001 maps while uploading, only because of the bad documentation on how to do it. This leads to new map names, because ppl think they broke something or don't get the versioning system. This increases the amount of trash maps in the vault and also the cleaning/hiding effort as well as mapper frustration. Also no information is given, so the mapper has no clue why his map is not working. 
2) I was able to upload maps like this before. And I like to continue naming some maps with a minus in special cases, e.g. location on a planet, special version, ... at least in the scenario name:
`name = "Adaptive Mars - Mangala Fossa",`
`name = "Adaptive Ahssa-Shi",`

Yeah @speed2CZ is right. The path in the .scmap file is not adapted. I encountered this problem with maps that have individual content such as decals in the map folder. In order to upload a working version the mapper has to ensure the right path before upload (think ahead). For example, if I like to upload v6 you have to replace all `.v0005` with `.v0006` in the scmap before upload. Otherwise the decals are displayed as missing.
![image](https://user-images.githubusercontent.com/28671151/62605992-8b025a00-b8fb-11e9-93e1-c9cb5c6a337e.png)

Here is my dream upload from a user perspective, which is basically a combination of solution 1 and 3:
**1) Check map content** 
Select map folder and read  `name = "map - name",` & `map_version = X;` from scenario.lua.
Display what upload will change in map folder and files, so the mapper can see the differences and knows what is actually happening. If something is wrong the uploading person should receive a warning, the upload should not be possible.
Maybe even check if maps with similar names exist and list them in order to explain versioning.

**2) Settings**
If the map passed the check 1), settings like ranked can be applied

**3) Upload**
Now its time to confirm the upload of the checked map.

**Comment by Brutus5000** [comment]
I totally agree that we lack serious amount of documentation. It took me way too long to figure out what currently happens. Whatever we do to fix the current state should be properly documented then in the FAF wiki and also here in the Github wiki of this app (maybe one links to the other).

I was not aware that the are paths inside the .scmap file. We could try to fix the foldernames there as well.

Regarding Solution 2:
Right now, if you upload the zip file, the API will extract it and the go through all `.lua` files and replaced `<old foldername>`  with `<new foldername>` (where `old foldername` name of the zip file without the file ending)
Example for `<old foldername>` in our example would be `haven_reef_-_faf_version`.

Right now in the scenario.lua you write:
`map = 'maps/haven_reef_-_faf_version/haven_reef_-_faf_version.scmap'`
My proposal is to write:
`map = 'maps/{MAPS_FOLDER}/haven_reef_-_faf_version.scmap'`
And this would be replaced during upload with the correct name. But you can't test a map with this map string.

**Comment by badbwoi** [comment]
I'm glad you agree.

##
**_about the scmap path:_**
I was unable to find a path in the scmap of a normal map (used notepad ++ again).
I'm not sure if that is only relevant if individual map content is linked, e.g. mirrored decals, ...

##
**_about the pathing in the files (scenario/script/scmap):_**
> Right now in the scenario.lua you write:
map = 'maps/haven_reef_-_faf_version/haven_reef_-_faf_version.scmap'

You are missing the versioning. I believe people should use the right path from the beginning, to understand how it works.

_right now its like that before upload..._

**folder**
`haven_reef_-_faf_version.v0002`

**scenario**
`name = "Haven Reef - FAF version",`
`map_version = 2,`
`map = 'maps/haven_reef_-_faf_version.v0002/haven_reef_-_faf_version.scmap',`

_additionally for special maps:_

**script** e.g. adaptive maps
`local Tables = import('/maps/adaptive_mars_-_mangala_fossa.v0002/adaptive_mars_-_mangala_fossa_tables.lua')`

**scmap** e.g. mirrored decals
`/maps/adaptive_ahssa-shi.v0005/flop_and_rotate_90/env/desert/decals/drycreek01lt_normals.dds`


I just tested my uploaded map and replaced all `_-_` in filenames and scenario with `___`.  I was able to play the map and saw the desired map name displayed in the lobby. So it seams to me the path is not written to the scmap for normal maps.
![image](https://user-images.githubusercontent.com/28671151/62619810-f0fcda80-b917-11e9-8a4c-dffefb5e044d.png)

But now if wondering why the map is even broken, I mean the path to the files is correct!?
![image](https://user-images.githubusercontent.com/28671151/62620934-db3ce480-b91a-11e9-84af-5db0cc4b99c0.png)

I tested some more and found that it only works as long as the same pattern is used in folder, file name and path. So either `_-_` or `___` or `_+-_` or `_` works for me. but a combination where folder and files differ leads to four-corners bug.
![image](https://user-images.githubusercontent.com/28671151/62621061-3ff83f00-b91b-11e9-90e8-f04d13d73c81.png)

**Comment by badbwoi** [comment]
First of all, thanks for your ideas and pov. I embrace the idea of a error free map upload, this would be awesome.

I talked to @CouncillorMorax and he told me that the character ban is also desired to get rid of map names like this: `name = "+++++canis_++++++"`

But completely disallowing `-` and `'` is a step backward in my eyes. I don't want to stall/complicate any progress, its just my personal feel to it. These are the only character I find useful for map names and they are even used in the original maps (e.g. X1MP_002 > `Williamson's Bridge`, SCMP_026 > `Vya-3 Protectorate`, SCMP_039 > `Four-Corners`). The original maps work like suggested, the folder and file names only contain `a-z`, `A-Z`, `0-9` and `_`, but a name with "special characters" in the scenario.lua.
![image](https://user-images.githubusercontent.com/28671151/62777740-a366a600-baae-11e9-98b0-82fc6288c85e.png)


Here are some ideas to enforce the desired scenario map name structure and build the right path from it. Its similar to @Brutus5000 option 3, solves naming issues @CouncillorMorax mentioned and still leaves us the option to replace e.g. `-` with `_` in folder, file and path:

1) Check scenario `name  = ""` string for allowed and illegal characters.
2) Count occurrence of "allowed special character" like `-` or  `'`
3) Result, see examples ...

**Example 1:** `name = "++++-§$++canis_+++++++-§$"`
invalid map name! > Change your map name!
`+`, `§`, `$`, are invalid/forbidden characters.
`-` can only be used once. 

**Example 2:** `name = "8----cani's's_--------"`
invalid map name! > Change your map name!
`8` the first character of the map name must be a letter.
`-` can only be used once.
`'` can only be used once.

**Example 3:** `name = "Haven Reef - FAF Version"`
valid map name!
Build/show correct path and file names **with or without** "allowed special character" `-`
`/maps/haven_reef___faf_version.v0002/haven_reef___faf_version...`
or
`/maps/haven_reef_-_faf_version.v0002/haven_reef_-_faf_version...`

**Example 4:** `name = "Ian's Cross"`
valid map name!
Build/show correct path and file names **without** "allowed special character" `'`
`/maps/ian_s_cross.v0001/ian_s_cross...`

_____________________________________________________________________________________________
A follow up question about versioning, if those character are not allowed anymore:
If the `-` gets banned, I'm unable to version my already uploaded maps properly, right? Meaning, I have to change the map name, what will create a new map. e.g.
`Ahssa-Shi` > `Ahssa Shi`
`Mars - Mangala Fossa` > `Mars Mangala Fossa`

**Comment by Brutus5000** [comment]
Should be fixed in the latest version. If new errors occur, please create a new issue.
