### ISSUE TITLE
api redirects the website to unencrypted login

### ISSUE THREAD

**Issue by jNullj** [micheljung/faf-java-api#334]
This is a followup on issue FAForever/website#193
In short, website sends the following GET request `https://api.faforever.com/oauth/authorize?response_type=code.....data...data....` after users clicks log in.
The API response with HTTP302(FOUND) and redirects to `http://api.faforever.com/login` insted of `https://api.faforever.com/login` , then username/password at login are sent unencrypted.

also `redirect_uri=https%3A%2F%2Fwww.faforever.com` in the request

**Comment by Brutus5000** [comment]
For more details see here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-use-tomcat-behind-a-proxy-server
