### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by Strogoo** [micheljung/faf-java-api#338]
Request 100 replays that have at least one 1500+ player:
https://api.faforever.com/data/game?page[number]=1&page[size]=100&sort=-startTime&filter=(playerStats.player.globalRating.rating%3Dgt%3D%221500%22)

And API returns 43.

Try 200 and it returns 89.
300 -> 134.
etc.

**Comment by Brutus5000** [comment]
I can confirm that the link above now returns 100 records as specified. :)
