### ISSUE TITLE
Migrate integration tests to junit5

### ISSUE THREAD

**Issue by norraxx** [micheljung/faf-java-api#344]
Now, all integration tests are implementing abstract class `com/faforever/api/AbstractIntegrationTest.java` that is based on junit4.

They're using
```java
@RunWith(SpringRunner.class)
```

Goal: migrate all integration tests at once to junit5.
Change ` org.junit.*` stuff to `org.junit.jupiter.api.*`.

**Comment by Brutus5000** [comment]
Woopsie duplicate (see #347)
