### ISSUE TITLE
Code cleanup of Spring components

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#348]
- [ ] Remove all `@Inject` and `@Autowired` annotations from the main modules (not the tests!). They are obsolete and no longer required.
- [ ] Replace hand-written constructors for these components with Lombok's `@AllArgsConstructor` or `@RequiredArgsConstructor` (where applicable - does not work in rare cases where the constructor is doing more than just assigning `private final` variables)
- [ ] Replace `@PostConstruct` and `@PreDestroy` methods -> add the interface implementations for `InitializingBean` and `DisposableBean` and move the code to the interface method.

**Comment by vaibhavthapliyal** [comment]
I would like to work on this issue.
