### ISSUE TITLE
ZipBombException for valid maps

### ISSUE THREAD

**Issue by andreasley** [micheljung/faf-java-api#365]
Some map file downloads don't work because of a ZipBombException.

According to https://github.com/FAForever/faf-java-api/issues/326, a ZipBombException occurs if the extracted file is more than 100x larger than the zip file. Unfortunately, this seems to be the case for some real maps. 

Example:
https://content.faforever.com/faf/vault/maps/crazyrush.v0003.zip
(10KB; expands to 1.3MB)

**Comment by Brutus5000** [comment]
Since you talk about download I guess this is a client issue?

**Comment by andreasley** [comment]
Correct; sorry about that. Wrong tab. :) I'll create an issue in the client.
