### ISSUE TITLE
Give M&M and Vault Maintenance Members Ability to Ban Vault Usage

### ISSUE THREAD

**Issue by CouncillorMorax** [micheljung/faf-java-api#380]
After some discussion with the Moderation councilor, we believe that a client ban on users for abusing the vaults and violating the rules is too harsh. A user that causes issue with the client vault should not be prohibited from playing the game, unless moderation believes they are directly affecting rulings on general FAF usage.

If possible, we would like for the ability to be given so that M&M members with access to mordor can prohibit users from uploading to vaults after repeat, or extreme, negligence to the rules.

**Comment by 1-alex98** [comment]
This first needs to be implemented in the server/api and then in the moderation client

**Comment by Brutus5000** [comment]
We could extend the enum that handles bans. Right now it has GLOBAL and CHAT. We could add another value VAULT there.
On db level it's a varchar, so no changes needed there, except for maybe the ban view?

**Comment by 1-alex98** [comment]
Well they also need to be kept from uploading then

**Comment by Brutus5000** [comment]
Was no varchar was enum, just added it to the db in [v85](https://github.com/FAForever/db/releases/tag/v85)
