### ISSUE TITLE
Internal Server error on request

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-api#383]
The following request throws 500

https://api.faforever.com/data/game?sort=-endTime&filter=playerStats.player.login==Explosive&include=mapVersion,mapVersion.map&fields[game]=mapVersion&fields[mapVersion]=map, thumbnailUrlLarge&fields[map]=displayName&page[limit]=10000

**Comment by bukajsytlos** [comment]
works on my machine :), @Brutus5000  logs?

**Comment by Brutus5000** [comment]
This is caused by https://github.com/FAForever/db/issues/215

**Comment by Brutus5000** [comment]
I'm closing this as nothing in the API can (or should) prevent this error.

**Comment by Brutus5000** [comment]
Query works now by the way.
