### ISSUE TITLE
Mods cannot be made rated

### ISSUE THREAD

**Issue by RK4000** [micheljung/faf-java-api#389]
![ss+(2020-04-01+at+07 24 50)](https://user-images.githubusercontent.com/7882150/78167427-c20b1a00-744e-11ea-8043-3ccf4a7862fc.png)

Should be self explanitory.

Vault mods cannot be made ranked.

**Comment by Brutus5000** [comment]
Stuff is back working since 6th of April (release of https://github.com/FAForever/faf-java-api/releases/tag/v2.7.6)
