### ISSUE TITLE
"FAF Map Authors" Whitelist Vault

### ISSUE THREAD

**Issue by CouncillorMorax** [micheljung/faf-java-api#411]
![image](https://user-images.githubusercontent.com/23299209/87942179-32739080-ca6a-11ea-9431-1bc79880b992.png)

Over the past year, the M&M team has collected a large amount of data and interactions with users, and sadly have come to the conclusion that too many are incapable/unwilling to follow basic rules of the maps and modifications vaults.

The resolution will be as follows:

1) Allow people to upload to a "dump" vault that does not show up in the search results so that anyone can host maps they want to try out.

2) The official vault is a whitelist vault where people who show they can abide by simple rules are allowed to upload whatever content they wish. Users will need be given permission by FAF account, traceable by the mordor client.

3) The M&M Top Picks remains to show top-level work.

**Comment by Brutus5000** [comment]
Solved in #472
