### ISSUE TITLE
Elide says collection has 65 pages in total but it has less

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-api#415]
Client issue:
https://github.com/FAForever/downlords-faf-client/issues/1868

Example query:
http://api.faforever.com/data/mod?sort=latestVersion.reviewsSummary.lowerBound&page[size]=20&page[totals]&page[number]=64

Shows that last page is empty also the pages 63 and a few others towards the end are empty. Be aware not all mods have a reviewsSummary.lowerBound which is probably the issue.

**Comment by 1-alex98** [comment]
We might open an issue on elide🤔 maybe with a minimal reproducable example

**Comment by 1-alex98** [comment]
My guess is that if you sort on a nullble property the entities being null are excluded but still counted in the page count

**Comment by bukajsytlos** [comment]
yeah might be. remember an issue where hibernate was doing cross join in
this case

**Comment by bukajsytlos** [comment]
yup https://lists.jboss.org/pipermail/hibernate-dev/2018-February/017299.html, will try to workaround it in elide
