### ISSUE TITLE
Username check for reserved username is broken

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#426]
As it turns out the check wether a username is reserved after renaming is broken.
https://github.com/FAForever/faf-java-api/blob/5ceaa8ca39d0ac2a7416d28becf6c43ab84931a9/src/main/java/com/faforever/api/user/NameRecordRepository.java#L15

`now()` should be smaller than `change date + x month` if a username is still reserved

**Comment by bukajsytlos** [comment]
from potential index perspective wouldn't it be better to compare `now() - x month < change_date` ?

**Comment by Brutus5000** [comment]
If we had an index, that might make sense :D
Will change it, maybe we add the index later.
