### ISSUE TITLE
Update gradle wrapper

### ISSUE THREAD

**Issue by bukajsytlos** [micheljung/faf-java-api#436]
At least jacoco in current version has issues with java 15

**Comment by Sheikah45** [comment]
same thing in client just added 
`//Specify jacoco version to work with java15
jacoco {
  toolVersion = "0.8.6"
}` 
to gradle files

**Comment by bukajsytlos** [comment]
yes, but I think it is better to update gradle, at least you have one less config which you don't have to manage

**Comment by Brutus5000** [comment]
There is never a reason not to update gradle (if it doesn't break CI)
