### ISSUE TITLE
Connect league service database via Elide Multiplex store

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#439]
The FAF league service stores it's data in a separate database on the same MySQL server.
Database host, username and password are the same, the database name is different

The tables are [here](https://github.com/FAForever/faf-league-service/blob/develop/migrations/V001__base.sql)

What we want to be able to query in Elide is:

- list of all leagues, seasons, division and subdivision (if possible leagues somehow with relationship to leaderboard)
- all score results of a player
- score changes per game
- all ranks of a player

**Comment by BlackYps** [comment]
I am not sure what you mean when you differentiate "all ranks" and "all score results" for a player
Right now I require the following queries for the client:

-List of all leagues
-List of all divisions for a given season
-The latest season of a given league
-List of all entries for a given division
-Entry for a given playerId and seasonId
