### ISSUE TITLE
Player spot API issue when fexible balance.

### ISSUE THREAD

**Issue by Kazbek** [micheljung/faf-java-api#462]
I found unexpeted behavior of gamePlayerStats StartSpot API. I guess flex balance (not opti) makes some wrong magic with sending data. Game #14433592 shows Kazbek-6spot and Aez-2, but in real we are on 1 and 4. For optimal balance shows correct positions.  At lobby Kazbek was on spot 3 and Aez was on spot 6.

**Comment by Brutus5000** [comment]
The API just returns what is written by the lobby server
