### ISSUE TITLE
Steam Link: Verify a play time of >2 h

### ISSUE THREAD

**Issue by Sheeo** [micheljung/faf-java-api#554]

**Comment by Brutus5000** [comment]
So players who bought it after registering and then encountering the Steam link requirements have to play Steam for 2hours? That's how you lose even more players during the process.

**Comment by Marc-Spector** [comment]
After linking the account, run the script after 6 - 24 hours only once and check again. Will it not work?

**Comment by BlackYps** [comment]
The return policy on steam is based on play time of the game. If your play time is less than 2 hours you can return the game. So no, just checking again after 24 hours will not suffice to fix this.

**Comment by Brutus5000** [comment]
It's also after an (undocumented) amount of weeks. But the Steam api doesn't give the purchase date as far as I can see.

**Comment by Brutus5000** [comment]
Also the user could have set the profile and/or game list private again.

**Comment by bukajsytlos** [comment]
I think there are no other solutions, than either having them already played for 2 hours before steamlink, or have some grace period after which verification has to be done again.

**Comment by Brutus5000** [comment]
There are no plans to implement this. The current solution is considered "good enough".
