### ISSUE TITLE
Use URL field of `mod_info.lua`

### ISSUE THREAD

**Issue by Garanas** [micheljung/faf-java-api#564]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Suggestion to show the URL field (if available). It can be found in the `mod_info.lua` file. As an example:
 - https://github.com/FAForever/Battle-Royale/blob/main/mods/battle-royale/mod_info.lua#L8

![image](https://user-images.githubusercontent.com/15778155/151428487-8361a8ef-efc9-400f-b0da-194e3913461e.png)

For example: somewhere below 'Authored by' / 'Uploaded by', next to the icon of the mod. That allows people to find the repository 😄 .

**Describe alternatives you've considered**
Adding it into the description - but then you can't click on it.

**Comment by Brutus5000** [comment]
This was added now, but it must be part of the API payload. Whether the client parses it from the mod_info.lua or takes it from a user field is not an api concern. @Sheikah45

**Comment by Hdt80bro** [comment]
Note that the mods manager recognizes a separate field for `github`, [see here](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/ModsManager.lua#L706).
