### ISSUE TITLE
Map Authors cannot hide their maps with basic scope

### ISSUE THREAD

**Issue by Sheikah45** [micheljung/faf-java-api#588]
Map Authors are getting a 403 error when trying to hide their map through the client.

Looking at the test server logs it seemed like it was still checking for the manage_vault scope even though they are the entity owner

**Comment by bukajsytlos** [comment]
@Sheikah45 can we get actual request? everything seems fine. Maybe there is something else in the request that is forbidden to change?

**Comment by Sheikah45** [comment]
Yeah you can also log in as any map author on the test server and get the error

**Comment by bukajsytlos** [comment]
I made api call on test api and it has worked
```
curl --request PATCH \
  --url https://api.test.faforever.com/data/mapVersion/64 \
  --header 'Authorization: Bearer token' \
  --header 'Content-Type: application/json' \
  --cookie JSESSIONID=C2770DA537137A70B33C9C3DFD97FBC5 \
  --data '{
  "data": {
		"type": "mapVersion",
    "id": "64",
    "attributes": {
      "hidden": true
    }
  }
}'

**Comment by Sheikah45** [comment]
This turned out to be a client issue
