### ISSUE TITLE
Allow API access to Elide for services without user authentication

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#793]
## Problem description

Due to ongoing DDoS attacks against API endpoints we protected the `/data` endpoints with `@Secured("ROLE_USER")`. However, this breaks external applications that were using the public parts of the API, such as the faf-website.

What we need is a way to authenticate services without a user context, so that these services can use the API just as before by providing _some_ kind of authentication.

## Solution ideas
There are 2 general approaches:

- Static API keys
- Oauth Access tokens for Machine2Machine authentication (hence no OpenID Connect, as there is no user component here).

OAuth access token seems the preferred approach, as along with their scopes, there is already a mechanism to limit the capabilities of access (if required). Also it is a global approach that could be used by all services wheres API key logic would need to go into each consumed service.

## OAuth approach issues
The current logic of the OAuth token parsing in the `FafAuthenticationConverter` requires the token to contain an integer subject (`sub` in the jwt) containing the FAF user id.
This would not match a machine2machine OAuth access token, as it has no user context.

We could think around setting the userId to a fallback value that does not map to a real user such as `-1`.
A cleaner solution would be to split up the `FafAuthenticationToken` into a `FafUserAuthenticationToken` and a `FafMachineAuthenticationToken`.

We could also think about setting a different role for machine (e.g. `ROLE_SERVICE` instead of `ROLE_USER` if it makes sense).

The biggest impact is probably in the permission checks of Elide where there the userId is no longer guaranteed to be available.

**Comment by fcaps** [comment]
@duk3luk3 we doing the oauth approach? if so, i could start updating the website.
