### ISSUE TITLE
[clan] updating a clan will not purge the cache

### ISSUE THREAD

**Issue by fcaps** [micheljung/faf-java-api#812]
there is an ux issue if the clan is getting updated (join/leave/edit) if will not show up directly due a 5min cache in elide.
is there something we can do without making it too complex?

the endpoint i am talking about `/data/clan/${id}?include=memberships.player`

**Comment by Brutus5000** [comment]
In the ClanService you need to inject the CacheManager and when you create/update/delete a clan, you need to get the cache with key `Clan.TYPE_NAME` and clear it.

**Comment by Sheikah45** [comment]
Why not just use @CacheEvict on the method?

**Comment by Brutus5000** [comment]
That might work too. Not the expert on caching
