### ISSUE TITLE
Add toString() methods for regularly logged entities

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#819]
- [ ] User -> print id and username
- [ ] Game -> print id and title

**Comment by dimitris1208** [comment]
I would like to contribute  :)

**Comment by Brutus5000** [comment]
Well then go for it!

**Comment by l3002** [comment]
Hi @Brutus5000, Could you please assign this issue to me? 
So, I can get started with toString() methods for the requested classes.

**Comment by l3002** [comment]
@Brutus5000 Just wanted to confirm if I need to override toString() methods for com.faforever.api.data.domain.User and com.faforever.api.data.domain.Game only.

**Comment by Brutus5000** [comment]
Correct. Also check out to use Lombok's @ToString

**Comment by l3002** [comment]
Sure and thanks for the clarification.

**Comment by l3002** [comment]
@Brutus5000  I've created a pull request for this issue. Kindly review it once you get time.
