### ISSUE TITLE
Improve handling of failed steam redirect validations

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#820]
On linking to Steam and on password reset via Steam, the user gets redirected to us from Steam with a code. We then ask the Steam API if the code is valid.

If it's not valid (rare case) this unfortunately leads to an internal server error (HTTP 500).
This should cause a bad request instead (HTTP 400) and the log should contain the user id and name (as we have some request in the forum that cannot be correlated to logs).

```
2024-01-08 17:01:15.724  WARN 1 --- [f895bed0-ec2d-4666-b4d6-405e6b907ce1] [io-8010-exec-87] c.f.a.e.GlobalControllerExceptionHandler : Internal server error

java.lang.IllegalArgumentException: Steam redirect could not be validated! Original response:
ns:http://specs.openid.net/auth/2.0
is_valid:false

        at com.faforever.api.user.SteamService.validateSteamRedirect(SteamService.java:82)
        at com.faforever.api.user.UsersController.requestPasswordResetViaSteam(UsersController.java:147)
```

The way to achieve this is to not throw an IllegalArgumentException, but log a useful error and throw an ApiException.of new type STEAM_LOGIN_VALIDATION_FAILED or something.

**Comment by Ivan-Shaml** [comment]
Hi, @Brutus5000 , currently when `ApiException` is thrown, it is handled by the following method `com.faforever.api.error.GlobalControllerExceptionHandler#processApiException` , which returns HTTP 422, not HTTP 400.

Is there any specific reason that this particular case should be handled differently and return HTTP 400 ?
If not, I have opened a PR, which is ready for review :) - #822

**Comment by Brutus5000** [comment]
HTTP 422 is totally fine. Quite a long time since I touched the error handling :D
