### ISSUE TITLE
On uploading map/mods add validation to map/mod version to be in range of 1..9999

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#908]
We had integer overflows causing weird file names and potentially errors in parsing of negative values in the clients.

The limit is the database:
* Maps max is 4 digits,
* Mods is SMALLINT (max 32767)

**Comment by Ivan-Shaml** [comment]
Hi,

As far as I undersand the issue, there are already existing records in the database for `com.faforever.api.data.domain.Mod` and `com.faforever.api.data.domain.Map`, which have invalid version numbers, so validation on entity level is not an option.

So in this case, additional validation logic needs to be added to the `MapService` and `ModService` classes for the upload methods.

Is my understanding correct ?

**Comment by Brutus5000** [comment]
Validation on entity level is too late and not suitable for proper error handling. We parse and validate a lua file inside the uploaded zip. MapService and ModService are the places to look for validation.

**Comment by Ivan-Shaml** [comment]
Thanks for the answer! When you have time (or any other maintainer), can you please take a look at the PR I have linked.

Especially at the new `ErrorCode` entries, I am not 100% sure if the messages are user friendly/appropriate.
